### ISSUE TITLE
Adult Content

### ISSUE THREAD

**Issue by area57** [basxto/daloader#3]
is there a possibility to download content which is flagged as mature and requieres a login?

**Comment by basxto** [comment]
Currently not.
It was possible in the past, but deviant art changed their API.

**Comment by basxto** [comment]
It’s now possible to login [via cookies](https://github.com/basxto/daloader/blob/master/daloader.example.ini). (inspired by [hb-downloader](https://github.com/talonius/hb-downloader))
The .ini file has to be in the working directory or a path has to be given with `--ini`.
There are addons to export browser cookies: [ExportCookies](https://github.com/rotemdan/ExportCookies) and [cookies.txt](https://github.com/lennonhill/cookies-txt)

This is not fully implemented yet. It does not work for images because the method, I used for downloading, does not support cookies.

edit: images don’t need cookies

**Comment by basxto** [comment]
I decided to directly support [cookies.txt](https://github.com/basxto/daloader#cookies), since the cookies seem to lose their validity often.
